### PR TITLE
Feature 66

### PR DESCRIPTION
**Pull request by gs-spadmanabhan**
A draft version of creating a flow definition and executing the flow using a Directed Graph. It has to be strictly a DAG for this to work. 

@benas Had to fix one bug hence creating a new PR

### CODE REVIEW

**Comment by benas** [comment]
Hi Sunand

Thank you for this PR! Let me check and get back to you.

Cheers
Mahmoud

**Comment by gs-spadmanabhan** [comment]
Hi @benas,

Just checking if you got a chance to take a look, its a rough version and not fully ready but if you have any comments on the approach/idea itself let me know.

Cheers!
Sunand

**Comment by benas** [comment]
Sorry, not yet. I'll try this weekend.

Thank you Sunand!

**Comment by gs-spadmanabhan** [comment]
`:ping` Did you get a chance?

**Comment by benas** [comment]
Yes! I find the end result elegant:

```java
FlowDefinition flowDefinition = new FlowDefinition();
final WorkflowGraph<Job> workflowGraph = flowDefinition
             .flow(job1, SUCCESS, job2)
             .flow(job1, SUCCESS, job3)
             .build();
 workflowGraph.breadthFirstSearch(workflowGraph.getRootVertex(), new JobVisitor());
```

but the implementation is quite complex. I understand roughly the idea: It's the breadth first search in a graph of jobs using the visitor pattern. But why not simply unmarshal a Json definition to a Java object as you mentioned [here](https://github.com/EasyBatch/easybatch-framework/issues/66#issuecomment-220893418)? This would be a lot easier to implement and more importantly to maintain. Do you agree?

 A couple of notes though:

* If we decide to go with a graph based approach (in contrast to sequential pipeline as I did with the JobPipeline), we should be able to start with multiples jobs (not only one root job). Does this implementation allows this?

* The `JobState` should be a predicate based on the job report, so that the user can implement its own transition conditions (80% of success for instance).

* This implementation should go first as a separate module under `easybatch-extensions`

Cheers
Mahmoud

**Comment by gs-spadmanabhan** [comment]
Hi @benas ,

Thank you for taking time in reviewing the code. Even if we unmarshall the Json definition to an Object it is very important to validate the Workflow Definition. My assumption is it will be directed from top to bottom with jobs executing in sequence or in parallel. This fits well for a graph use case if not I am not able to visualize how to code elegantly. Please suggest if you have any thoughts around it.

`we should be able to start with multiples jobs (not only one root job). Does this implementation allows this?`

Presently this implementation does not solve the above condition. But I will definitely take a look at it.

`The JobState should be a predicate based on the job report, so that the user can implement its own transition conditions (80% of success for instance).`

I completely agree to the above statement.

`easybatch-extensions` As for the implementation yes it can go in to separate module plus separate out the graph code in to an util only have the Flow Definition and the `JobVisitor `code at the top level in this module. 

In `JobVisitor `we can further implement job execution to happen in parallel if the number of outgoing edges are greater than 1 for a job having a success or failure state.

Cheers!
Sunand

**Pull request closed without merging**
