### PR TITLE
FormatDuration Now Includes Days

### PR DESCRIPTION
**Pull request by ipropper**
Altered the formatDuration code so that it includes days. Jobs that take over 24 hours will now properly display the total time. There is no cap on the total length of the duration.

### CODE REVIEW

**Comment by ipropper** [comment]
While creating the above pull request I noticed that the `OutputStreamRecordWriterTest.outputStreamRecordWriterIntegrationTest`  failed on my system.
This test failed before I made changes. I would be happy to look into why this test failed,

**Comment by benas** [comment]
Fantastic! Thank you very much.
I like this assertion: https://github.com/j-easy/easy-batch/pull/294/files#diff-69a66629aa91dd31d3cab73bf1bfd735R67 😄 

I think we should also update this test: `HtmlJobReportFormatterTest.testReportFormatting` (which is failing on travis-ci). Don't hesitate to add yourself to the contributors list in the readme and your PR is ready to be merged.

> OutputStreamRecordWriterTest.outputStreamRecordWriterIntegrationTest failed on my system.

On which system are you working?

**Comment by ipropper** [comment]
Sorry about that, I still can't quite use mvn package, a couple tests fail.

I am running on windows 10,
Java version 1.8.0_144
maven version 3.5.0

Right now easybatch-univocity fails when i run mvn package.

**Comment by benas** [comment]
Hi @ipropper 

Your changes are not the cause of build failure on windows. I've fixed the build and added a CI service using appveyor for windows (in addition to travis ci for unix/linux).

I've merged your PR and I will include in next release. Thank you for your time and effort!

Kr
Mahmoud

**Pull request merged**
