### PR TITLE
Add CountedFileRecordReader feature.

### PR DESCRIPTION
**Pull request by DanieleS82**
The new record reader is a decorator for all readers that implement the _AbstractFileRecordReader_ interface that provide the number of the rows into the file. The real file record is wrapped from the new component that internally use it to perform the job.

### CODE REVIEW

**Comment by benas** [comment]
Hi,

The `Record` abstraction represents a logical record in the input file which might span multiple physical lines. For example, the following xml file:

```xml
<tweets>
   <tweet>
      <data>...</data>
   </tweet>
   <tweet>
      <data>...</data>
   </tweet>
</tweets
```

contains 2 xml records but 8 lines. Same case for Json or Yaml records.
Hence the method `Utils.countRows` would work for flat files but not for hierarchical ones.
Do you agree?

FYI, in a [previous version](https://github.com/j-easy/easy-batch/commit/c336c6bf630815dae8038ffc201b2fa4c09da572), the record reader had a method to calculate the number of records in the datasource. Easy Batch was calculating the total number of records in the beginning, then start processing the file. This two pass process was not efficient and that's why it was removed.

In this PR, how would the new `CountedFileRecordReader` be used? Easy Batch will give the total number of records in the job report anyway.

Kr
Mahmoud

**Comment by DanieleS82** [comment]
Hi,
yes this is true and in a first version of the component I wrote it as abstract class where the _countRows(...)_ method must to be provided from the final user. In order to introduce the feature I thought could be useful to provide a default implementation, although it limits the usage of the component to specific type (I think this component is more useful for flat file in this moment).
I wrote this component because I have flat files where I need to filter a subset of rows, the first one and the last _X_ rows. With the existing component, I can specify the number of the record I want to remove, but the problem is that I haven't the length of the file. 
So, the solution I choose is pre-calculate this info before starting to process the file. In my case, I use the new component to calculate the length of the file and then I use info calculated to provide as input to your component the number of the rows must to be skipped.
As regards info provided by Easy Batch are little different, at the moment it gives the number of the record processed, skipped, ecc, do you agree?
I agree with you to provide this info by default is not efficient. Achieve them with a separate component, allow to introduce this effort only if really needed.

What do you think about it?

**Comment by benas** [comment]
> So, the solution I choose is pre-calculate this info before starting to process the file.

I used the same idea to implement the progress listener tutorial (see [here](https://github.com/j-easy/easy-batch/blob/1b4e5bed47e8b1de6e5802e34d664e4aae0fca06/easybatch-tutorials/src/main/java/org/easybatch/tutorials/advanced/jmx/ProgressListener.java#L16)).

If you want to calculate the total number of records *before starting the job*, why don't you do something like:

```java
int rowCount = 0;
while (recordReader.readRecord() != null) {
   rowCount++;
}
```

This should give you the total number of records even if they span multiple lines (as in a xml file when the recordReader is an XmlRecordReader for instance).

If you want to get the row count *after the job is finished*, you can get this from `JobMetris.getReadCount`.

**Comment by DanieleS82** [comment]
Yes, I saw your solution but the problem with _Scanner_ is slow. In my example I have more 1.200.000 rows/records and using a _BufferedInputStream_, the size is retrieve in less 1 second, with _Scanner_ are require some seconds. Two link that cover this aspect:
1. https://stackoverflow.com/questions/453018/number-of-lines-in-a-file-in-java
2. https://stackoverflow.com/questions/2231369/scanner-vs-bufferedreader

What do you think?

**Comment by benas** [comment]
> Yes, I saw your solution but the problem with Scanner is slow

Yes indeed! I am aware of that. That was a tutorial, so not really an issue. But it is planned to replace the usage of `scanner` in `FlatFileRecordReader` with a `BufferedReader`.

Back to this PR, you suggest to add a `CountedFileRecordReader` to count the total number of records. As mentioned, this can be done using any reader with:

```java
while (recordReader.readRecord() != null) rowCount++;
```

Also, the current PR works only for flat files which is not consistent with other record types. So I'm closing this issue for now. Thank you for your help!

Kr
Mahmoud

**Comment by DanieleS82** [comment]
I wrote this component to cover the case where is need to know before the number of the rows contained in the file and later use this value connected with the new component _FilteredRecordsSavingRecordFilter_ in this way:
```java
CountedFileRecordReader cf = new CountedFileRecordReader(new FlatFileRecordReader(...));
FilteredRecordsSavingRecordFilter anagRecordFilter = new FilteredRecordsSavingRecordFilter(
        new RecordNumberEqualToFilter(1, cf.getRowsNumber() - 1, cf.getRowsNumber()));
```
Your loop works but give the info only after entered in the pipeline that process the records, and I need it before. How do you suggest to do it?

At the moment yes, I covered only the flat file to expose you the idea, but if you think could be usefull, we can improve the implementation to cover some basic types and give at the final user a way to implements others specific format.

What do you think?

**Comment by benas** [comment]
Yes I see, the PR adds a public static method to the utils class: ` Utils.countRows(this.delegate.file);` and call it in the `CountedFileRecordReader` constructor.

So instead of adding a new component, instantiate it, and call `getRowsNumber` on it, you do something like:

```java
int rowNumber = Utils.countRows(yourFile);
FilteredRecordsSavingRecordFilter anagRecordFilter = new FilteredRecordsSavingRecordFilter(
        new RecordNumberEqualToFilter(1, rowNumber - 1, rowNumber));
```

> At the moment yes, I covered only the flat file to expose you the idea, but if you think could be usefull, we can improve the implementation to cover some basic types and give at the final user a way to implements others specific format.
> What do you think?

No I don't think we need this component. Because, each time we create a reader, it will go through all the file to calculate the number of records at construction time: https://github.com/j-easy/easy-batch/pull/302/files#diff-cf276d5f15384f8d584db6cbafbd2e3aR51 . This means the file will be read twice: Once when we create the component, and antoher time when the job is executed. In the case you mentioned with 1.200.000 lines flat file or with a huge XML file, just creating the reader `Reader reader = new CountedRecordReader(myReader);` will go though the whole file.

Your use case is a valid one! But this is a specific requirement and can be done with one extra line: either your `Utils.countRows` for flat files or `while (recordReader.readRecord() != null) rowCount++;` which would work for any kind of supported files. We don't need to add a component for that.

**Pull request closed without merging**
